version: "3.6"
services:
  frontend:
    image: initedit/note.initedit:0.1
    environment:
      NOTE_API_BACKEND:
    ports:
      - 80:80
    depends_on:
     - backend

  backend:
    image: initedit/api.note.initedit:0.1
    environment:
      - API_NOTE_DATABASE=db
      - DB_PORT=3306
      - DB_DATABASE=initedit
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    ports:
      - 8000:80
    depends_on:
     - merge

  merge:
    image: initedit/api.note.initedit:0.1
    environment:
      - API_NOTE_DATABASE=db
      - DB_PORT=3306
      - DB_DATABASE=initedit
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    command: migrate
    restart: on-failure:10
    depends_on:
     - db

  db:
    image: mysql:8.0.30
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=initedit
    ports:
      - 3306:3306