name: Docker

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: 🐳 Login to DockerHub
      if: ${{ github.event_name == 'push' }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Tag Variables
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }}
      id: tag-variables
      run: |
        echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: 'amd64,arm64'

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push (latest)
      if: ${{ github.event_name == 'push' }}
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: initedit/note.initedit:latest
        target: ${{ matrix.target }}
        cache-from: type=registry,ref=initedit/note.initedit:latest
        cache-to: type=inline

    - name: Build and push (tag)
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }}
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: initedit/note.initedit:${{ steps.tag-variables.outputs.tag }}
        target: ${{ matrix.target }}
        cache-from: type=registry,ref=initedit/note.initedit:latest
        cache-to: type=inline
